package org.ionproject.android.common.ionwebapi

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.withContext
import java.net.URI
import java.net.URISyntaxException
import kotlin.random.Random

private const val PROGRAMMES_PATH_V0 = "/v0/programmes"
private const val COURSES_PATH_V0 = "/v0/courses"
private const val CLASSES_PATH = "/classes"
private const val COURSES_PATH = "/courses"
private const val OFFERS_PATH = "/offers"
private const val CALENDAR_TERMS_PATH_V0 = "/v0/calendar-terms"
private const val ROOT_PATH_V0 =
    "/v0" //TODO We should consider using "/" instead to support the most recent version

class MockIonWebAPI(private val ionMapper: IIonMapper) : IIonWebAPI {

    override suspend fun <T> getFromURI(uri: URI, klass: Class<T>): T {
        val responseBody: String = get(uri)
        return ionMapper.parse(responseBody, klass)
    }

    /**
     *  This is using the IO Dispacher, which is optimized to perform disk or network I/O
     *  outside of the main thread. Examples include using the Room component,
     *  reading from or writing to files, and running any network operations.
     */
    private suspend fun get(uri: URI): String =
        withContext(Dispatchers.IO) {
            //Chaos filter which simulates request delay, from 50ms to 500ms
            val randomdelay = Random.nextLong(50, 500)
            delay(randomdelay)
            route(uri)
        }

    private fun route(uri: URI): String = when (uri.path) {
        ROOT_PATH_V0 -> root
        PROGRAMMES_PATH_V0 -> allProgrammesMock
        COURSES_PATH_V0 -> allCoursesMock
        "${PROGRAMMES_PATH_V0}/1" -> leicMock
        "${PROGRAMMES_PATH_V0}/1${OFFERS_PATH}/1" -> pgOfferMock
        "${PROGRAMMES_PATH_V0}/1${OFFERS_PATH}/2" -> lsdOfferMock
        "${PROGRAMMES_PATH_V0}/1${OFFERS_PATH}/3" -> m1OfferMock
        "${PROGRAMMES_PATH_V0}/1${OFFERS_PATH}/4" -> algaOfferMock
        "${PROGRAMMES_PATH_V0}/1${OFFERS_PATH}/5" -> eOfferMock
        "${COURSES_PATH_V0}/1" -> pgMock
        "${COURSES_PATH_V0}/2" -> lsdMock
        "${COURSES_PATH_V0}/3" -> m1Mock
        "${COURSES_PATH_V0}/4" -> algaMock
        "${COURSES_PATH_V0}/5" -> eMock
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v" -> pgClassesMock
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v" -> lsdClassesMock
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v" -> m1ClassesMock
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v" -> algaClassesMock
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v" -> eClassesMock
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/11D" -> pgClassSection11DMock
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/12D" -> pgClassSection12DMock
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/11N" -> pgClassSection11NMock
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v/11D" -> lsdClassSection11DMock
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v/12D" -> lsdClassSection12DMock
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v/11N" -> lsdClassSection11NMock
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v/11D" -> m1ClassSection11DMock
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v/12D" -> m1ClassSection12DMock
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v/11N" -> m1ClassSection11NMock
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v/11D" -> algaClassSection11DMock
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v/12D" -> algaClassSection12DMock
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v/11N" -> algaClassSection11NMock
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v/11D" -> eClassSection11DMock
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v/12D" -> eClassSection12DMock
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v/11N" -> eClassSection11NMock
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/calendar/1234" -> pg1stexam
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/calendar/1235" -> pg2ndexam
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v/calendar/1236" -> lsd1stexam
        "${COURSES_PATH_V0}/2${CLASSES_PATH}/1920v/calendar/1237" -> lsd2ndexam
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v/calendar/1240" -> m1FirstExam
        "${COURSES_PATH_V0}/3${CLASSES_PATH}/1920v/calendar/1241" -> m1SecondExam
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v/calendar/1238" -> alga1stExam
        "${COURSES_PATH_V0}/4${CLASSES_PATH}/1920v/calendar/1239" -> alga2ndExam
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v/calendar/1242" -> e1stExam
        "${COURSES_PATH_V0}/5${CLASSES_PATH}/1920v/calendar/1243" -> e2ndExam
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/11D/calendar" -> pg11Dlectures
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/calendar/123490" -> pg11DWorkAssignment1
        "${COURSES_PATH_V0}/1${CLASSES_PATH}/1920v/calendar/123497" -> pgExamJournal
        CALENDAR_TERMS_PATH_V0 -> calendarTermsMock
        else -> throw URISyntaxException(uri.path, "Uri not implemented or invalid")
    }

}

/**
 *  Computer generated mocks
 */
// JSON Home root representation
private const val root = "{ \"api\": { \"title\": \"i-on Core\", \"links\": { \"describedBy\": \"https://github.com/i-on-project/core/tree/master/docs/api\" } }, \"resources\": { \"courses\": { \"hrefTemplate\": \"/v0/courses{?page,limit}\", \"hrefVars\": { \"limit\": \"/api-docs/params/limit\", \"page\": \"/api-docs/params/page\" }, \"hints\": { \"allow\": [\"GET\"], \"formats\": { \"application/vnd.siren+json\":{} }, \"docs\": \"https://github.com/i-on-project/core/tree/master/docs/api/courses.md\" } }, \"programmes\": { \"hrefTemplate\": \"/v0/programmes{?page,limit}\", \"hrefVars\": { \"limit\": \"/api-docs/params/limit\", \"page\": \"/api-docs/params/page\" }, \"hints\": { \"allow\": [\"GET\"], \"formats\": { \"application/vnd.siren+json\":{} }, \"docs\": \"https://github.com/i-on-project/core/tree/master/docs/api/programme.md\" } }, \"calendar-terms\": { \"hrefTemplate\": \"/v0/calendar-terms{?page,limit}\", \"hrefVars\": { \"limit\": \"/api-docs/params/limit\", \"page\": \"/api-docs/params/page\" }, \"hints\": { \"allow\": [\"GET\"], \"formats\": { \"application/vnd.siren+json\":{} }, \"docs\": \"https://github.com/i-on-project/core/blob/master/docs/api/calendar-terms.md\" } } } }"

// All programmes
private const val allProgrammesMock =
    "{ \"class\": [ \"collection\", \"programme\" ], \"entities\": [ { \"class\": [ \"programme\" ], \"rel\": [ \"item\" ], \"properties\": { \"id\": 1, \"acronym\": \"LEIC\" }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1\" } ] }, { \"class\": [ \"Programme\" ], \"rel\": [ \"item\" ], \"properties\": { \"id\": 2, \"acronym\": \"MEIC\" }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/2\" } ] } ], \"actions\": [ { \"name\": \"add-programme\", \"title\": \"Add Programme\", \"method\": \"POST\", \"href\": \"/v0/programmes/\", \"type\": \"application/json\", \"fields\": [ { \"name\": \"ProgrammeAcr\", \"type\": \"text\"}, { \"name\": \"TermSize\", \"type\": \"number\"} ] } ], \"links\": [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes\" } ] }"

// Programme Details
private const val leicMock =
    "{ \"class\": [ \"programme\" ], \"properties\": { \"id\": 1, \"name\": \"Licenciatura em Engenharia Informática e de Computadores\", \"acronym\": \"LEIC\", \"termSize\": 6 }, \"entities\": [ { \"class\": [ \"offer\" ], \"title\": \"PG Offer\", \"rel\": [ \"/rel/programmeOffer\" ], \"properties\": { \"id\": 1, \"courseId\": 1, \"termNumber\": 1 }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1/offers/1\"} ] }, { \"class\": [ \"offer\" ], \"title\": \"LSD Offer\", \"rel\": [ \"/rel/programmeOffer\" ], \"properties\": { \"id\": 2, \"courseId\": 2, \"termNumber\": 1 }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1/offers/2\"} ] }, { \"class\": [ \"offer\" ], \"title\": \"M1 Offer\", \"rel\": [ \"/rel/programmeOffer\" ], \"properties\": {\"id\": 3,  \"courseId\": 3, \"termNumber\": 1 }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1/offers/3\"} ] }, { \"class\": [ \"offer\" ], \"title\": \"ALGA Offer\", \"rel\": [ \"/rel/programmeOffer\" ], \"properties\": {\"id\": 4, \"courseId\": 4, \"termNumber\": 1 }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1/offers/4\"} ] }, { \"class\": [ \"offer\" ], \"title\": \"E Offer\", \"rel\": [ \"/rel/programmeOffer\" ], \"properties\": {\"id\": 5, \"courseId\": 5, \"termNumber\": 1 }, \"links\" : [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1/offers/5\"} ] } ], \"actions\": [ { \"name\": \"edit-programme\", \"title\": \"Edit Programme\", \"method\": \"PUT\", \"href\": \"/v0/programmes/1\", \"type\": \"application/json\", \"fields\": [ { \"name\": \"ProgrammeName\", \"type\": \"text\"}, { \"name\": \"Acronym\", \"type\": \"text\"}, { \"name\": \"TermSize\", \"type\": \"number\"} ] }, { \"name\": \"add-offer\", \"title\": \"Add Offer\", \"method\": \"POST\", \"href\": \"/v0/programmes/1/offers\", \"type\": \"application/json\", \"fields\": [ { \"name\": \"CourseId\", \"type\": \"number\"}, { \"name\": \"CurricularTerm\", \"type\": \"number\" }, { \"name\": \"Optional\", \"type\": \"boolean\"} ] } ], \"links\": [ { \"rel\": [ \"self\" ], \"href\": \"/v0/programmes/1\" }, { \"rel\": [ \"up\" ], \"href\": \"/v0/programmes\" } ] }"

// Programme Offers
private const val pgOfferMock =
    "{\"class\":[\"offer\"],\"properties\":{\"id\":1,\"acronym\":\"PG\",\"termNumber\":1,\"optional\":false},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"/rel/course/\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1\"}]}],\"actions\":[{\"name\":\"edit\",\"title\":\"EditOffer\",\"method\":\"PUT\",\"type\":\"application/json\",\"href\":\"/v0/programmes/1/offers/1\",\"fields\":[{\"name\":\"Acronym\",\"type\":\"text\"},{\"name\":\"TermNumber\",\"type\":\"number\"},{\"name\":\"Optional\",\"type\":\"boolean\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/programmes/1/offers/1\"},{\"rel\":[\"related\"],\"href\":\"/v0/programmes/1\"}]}"
private const val lsdOfferMock =
    "{\"class\":[\"offer\"],\"properties\":{\"id\":2,\"acronym\":\"LSD\",\"termNumber\":1,\"optional\":false},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"/rel/course/\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2\"}]}],\"actions\":[{\"name\":\"edit\",\"title\":\"EditOffer\",\"method\":\"PUT\",\"type\":\"application/json\",\"href\":\"/v0/programmes/1/offers/2\",\"fields\":[{\"name\":\"Acronym\",\"type\":\"text\"},{\"name\":\"TermNumber\",\"type\":\"number\"},{\"name\":\"Optional\",\"type\":\"boolean\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/programmes/1/offers/2\"},{\"rel\":[\"related\"],\"href\":\"/v0/programmes/1\"}]}"
private const val m1OfferMock =
    "{\"class\":[\"offer\"],\"properties\":{\"id\":3,\"acronym\":\"M1\",\"termNumber\":1,\"optional\":false},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"/rel/course/\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3\"}]}],\"actions\":[{\"name\":\"edit\",\"title\":\"EditOffer\",\"method\":\"PUT\",\"type\":\"application/json\",\"href\":\"/v0/programmes/1/offers/3\",\"fields\":[{\"name\":\"Acronym\",\"type\":\"text\"},{\"name\":\"TermNumber\",\"type\":\"number\"},{\"name\":\"Optional\",\"type\":\"boolean\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/programmes/1/offers/3\"},{\"rel\":[\"related\"],\"href\":\"/v0/programmes/1\"}]}"
private const val algaOfferMock =
    "{\"class\":[\"offer\"],\"properties\":{\"id\":4,\"acronym\":\"ALGA\",\"termNumber\":1,\"optional\":false},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"/rel/course/\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4\"}]}],\"actions\":[{\"name\":\"edit\",\"title\":\"EditOffer\",\"method\":\"PUT\",\"type\":\"application/json\",\"href\":\"/v0/programmes/1/offers/4\",\"fields\":[{\"name\":\"Acronym\",\"type\":\"text\"},{\"name\":\"TermNumber\",\"type\":\"number\"},{\"name\":\"Optional\",\"type\":\"boolean\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/programmes/1/offers/4\"},{\"rel\":[\"related\"],\"href\":\"/v0/programmes/1\"}]}"
private const val eOfferMock =
    "{\"class\":[\"offer\"],\"properties\":{\"id\":5,\"acronym\":\"E\",\"termNumber\":1,\"optional\":false},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"/rel/course/\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5\"}]}],\"actions\":[{\"name\":\"edit\",\"title\":\"EditOffer\",\"method\":\"PUT\",\"type\":\"application/json\",\"href\":\"/v0/programmes/1/offers/5\",\"fields\":[{\"name\":\"Acronym\",\"type\":\"text\"},{\"name\":\"TermNumber\",\"type\":\"number\"},{\"name\":\"Optional\",\"type\":\"boolean\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/programmes/1/offers/5\"},{\"rel\":[\"related\"],\"href\":\"/v0/programmes/1\"}]}"

// All courses
private const val allCoursesMock =
    "{\"class\":[\"course\",\"collection\"],\"properties\":{},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"id\":1,\"acronym\":\"PG\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]},{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"id\":2,\"acronym\":\"LSD\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]},{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"id\":3,\"acronym\":\"M1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/3/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]},{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"id\":4,\"acronym\":\"ALGA\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/4/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]},{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"id\":5,\"acronym\":\"E\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/5/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}],\"actions\":[{\"name\":\"add-item\",\"title\":\"Add a new Course\",\"method\":\"POST\",\"href\":\"/v0/courses\",\"isTemplated\":false,\"type\":\"application/json\",\"fields\":[]},{\"name\":\"search\",\"title\":\"Search items\",\"method\":\"GET\",\"href\":\"/v0/courses{?limit,page}\",\"isTemplated\":true,\"type\":\"application/vnd.siren+json\",\"fields\":[{\"name\":\"limit\",\"type\":\"number\",\"class\":\"param/limit\"},{\"name\":\"page\",\"type\":\"number\",\"class\":\"param/page\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses?page=1&limit=2\"},{\"rel\":[\"next\"],\"href\":\"/v0/courses?page=2&limit=2\"},{\"rel\":[\"previous\"],\"href\":\"/v0/courses?page=0&limit=2\"}]}"

// Courses
private const val pgMock =
    "{\"class\":[\"course\"],\"properties\":{\"id\":1,\"acronym\":\"PG\",\"name\":\"Programa\u00e7\u00e3o\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"/rel/class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/1\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/1\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}"
private const val lsdMock =
    "{\"class\":[\"course\"],\"properties\":{\"id\":2,\"acronym\":\"LSD\",\"name\":\"Lógica de Sistemas de Digitais\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"/rel/class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/2\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/2\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/2\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}"
private const val m1Mock =
    "{\"class\":[\"course\"],\"properties\":{\"id\":3,\"acronym\":\"M1\",\"name\":\"Matemática I\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"/rel/class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/3\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/3\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/3\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/3/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}"
private const val algaMock =
    "{\"class\":[\"course\"],\"properties\":{\"id\":4,\"acronym\":\"ALGA\",\"name\":\"Álgebra Linear e Geometria Analítica\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"/rel/class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/4\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/4\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/4\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/4/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}"
private const val eMock =
    "{\"class\":[\"course\"],\"properties\":{\"id\":5,\"acronym\":\"E\",\"name\":\"Eletrónica\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"/rel/class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/5\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/5\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/5\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/5/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses\"}]}"

// Course classes
private const val pgClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"courseAcr\":\"PG\",\"courseId\":1,\"calendarTerm\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":1,\"courseAcr\":\"PG\",\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":1,\"courseAcr\":\"PG\",\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/12D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":1,\"courseAcr\":\"PG\",\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11N\"}]},{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/1/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"*/*\",\"href\":\"/v0/courses/1/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/1/classes/\"}]}"
private const val lsdClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"courseAcr\":\"LSD\",\"courseId\":2,\"calendarTerm\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":2,\"courseAcr\":\"LSD\",\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":2,\"courseAcr\":\"LSD\",\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/12D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":2,\"courseAcr\":\"LSD\",\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11N\"}]},{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/2/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"*/*\",\"href\":\"/v0/courses/2/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/2/classes/\"}]}"
private const val m1ClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"courseAcr\":\"M1\",\"courseId\":3,\"calendarTerm\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":3,\"courseAcr\":\"M1\",\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":3,\"courseAcr\":\"M1\",\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/12D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":3,\"courseAcr\":\"M1\",\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11N\"}]},{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/3/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"*/*\",\"href\":\"/v0/courses/3/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/3/classes/\"}]}"
private const val algaClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"courseAcr\":\"ALGA\",\"courseId\":4,\"calendarTerm\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":4,\"courseAcr\":\"ALGA\",\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":4,\"courseAcr\":\"ALGA\",\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/12D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":4,\"courseAcr\":\"ALGA\",\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11N\"}]},{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/4/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"*/*\",\"href\":\"/v0/courses/4/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/4/classes/\"}]}"
private const val eClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"courseAcr\":\"E\",\"courseId\":5,\"calendarTerm\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":5,\"courseAcr\":\"E\",\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":5,\"courseAcr\":\"E\",\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/12D\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"courseId\":5,\"courseAcr\":\"E\",\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"rel\":[\"item\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11N\"}]},{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/5/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"*/*\",\"href\":\"/v0/courses/5/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/5/classes/\"}]}"

// Class Section
private const val pgClassSection11DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"PG\",\"courseId\":1,\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11d/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/1/classes/1920v/11d/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11d\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private const val pgClassSection12DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"PG\",\"courseId\":1,\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/12D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/1/classes/1920v/12D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/12D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private const val pgClassSection11NMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"PG\",\"courseId\":1,\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11N/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/1/classes/1920v/11N/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/11N\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}\n"

private const val lsdClassSection11DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"LSD\",\"courseId\":2,\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/2/classes/1920v/11D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/2/classes/1920v\"}]}\n"
private const val lsdClassSection12DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"LSD\",\"courseId\":2,\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/12D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/2/classes/1920v/12D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/12D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/2/classes/1920v\"}]}\n"
private const val lsdClassSection11NMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"LSD\",\"courseId\":2,\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11N/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/2/classes/1920v/11N/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/2/classes/1920v/11N\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/2/classes/1920v\"}]}\n"

private const val m1ClassSection11DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"M1\",\"courseId\":3,\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/3/classes/1920v/11D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/3/classes/1920v\"}]}\n"
private const val m1ClassSection12DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"M1\",\"courseId\":3,\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/12D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/3/classes/1920v/12D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/12D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/3/classes/1920v\"}]}\n"
private const val m1ClassSection11NMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"M1\",\"courseId\":3,\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11N/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/3/classes/1920v/11N/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/3/classes/1920v/11N\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/3/classes/1920v\"}]}\n"

private const val algaClassSection11DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"ALGA\",\"courseId\":4,\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/4/classes/1920v/11D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/4/classes/1920v\"}]}\n"
private const val algaClassSection12DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"ALGA\",\"courseId\":4,\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/12D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/4/classes/1920v/12D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/12D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/4/classes/1920v\"}]}\n"
private const val algaClassSection11NMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"ALGA\",\"courseId\":4,\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11N/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/4/classes/1920v/11N/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/4/classes/1920v/11N\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/4/classes/1920v\"}]}\n"

private const val eClassSection11DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"E\",\"courseId\":5,\"calendarTerm\":\"1920v\",\"id\":\"11D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/5/classes/1920v/11D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/5/classes/1920v\"}]}\n"
private const val eClassSection12DMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"E\",\"courseId\":5,\"calendarTerm\":\"1920v\",\"id\":\"12D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/12D/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/5/classes/1920v/12D/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/12D\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/5/classes/1920v\"}]}\n"
private const val eClassSection11NMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"courseAcr\":\"E\",\"courseId\":5,\"calendarTerm\":\"1920v\",\"id\":\"11N\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11N/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"method\":\"DELETE\",\"href\":\"/v0/courses/5/classes/1920v/11N/\",\"type\":\"*/*\",\"isTemplated\":false,\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/5/classes/1920v/11N\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/5/classes/1920v\"}]}\n"

//Calendar terms
private const val calendarTermsMock =
    "{\"class\":[\"calendar-term\",\"collection\"],\"properties\":{},\"entities\":[{\"class\":[\"term\"],\"rel\":[\"item\"],\"properties\":{\"name\":\"1920v\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/calendar-terms/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/calendar-terms\"}]},{\"class\":[\"term\"],\"rel\":[\"item\"],\"properties\":{\"name\":\"1920i\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/calendar-terms/1920i\"},{\"rel\":[\"collection\"],\"href\":\"/v0/calendar-terms\"}]}],\"actions\":[{\"name\":\"Search\",\"title\":\"Search items\",\"method\":\"GET\",\"href\":\"/v0/calendar-terms{?page,limit}\",\"isTemplated\":true,\"type\":\"application/vnd.siren+json\",\"fields\":[{\"name\":\"limit\",\"type\":\"number\",\"class\":\"param/limit\"},{\"name\":\"page\",\"type\":\"number\",\"class\":\"param/page\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/calendar-terms?page=1&limit=2\"},{\"rel\":[\"next\"],\"href\":\"/v0/calendar-terms?page=2&limit=2\"},{\"rel\":[\"previous\"],\"href\":\"/v0/calendar-terms?page=0&limit=2\"}]}"

// Exam mocks (Events)
private val pg1stexam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1234\"},\"summary\":{\"value\":\"PG 1st Exam\"},\"description\":{\"value\":\"First exam of the PG course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-19T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-19T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1234\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private val pg2ndexam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1235\"},\"summary\":{\"value\":\"PG 2nd Exam\"},\"description\":{\"value\":\"Second exam of the PG course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-06-11T14:00:00Z\"},\"dtend\":{\"value\":\"2020-06-11T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1235\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

private val lsd1stexam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1236\"},\"summary\":{\"value\":\"LSD 1st Exam\"},\"description\":{\"value\":\"First exam of the LSD course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-06-12T14:00:00Z\"},\"dtend\":{\"value\":\"2020-06-12T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1236\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private val lsd2ndexam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1237\"},\"summary\":{\"value\":\"LSD 2nd Exam\"},\"description\":{\"value\":\"Second exam of the LSD course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-06-13T14:00:00Z\"},\"dtend\":{\"value\":\"2020-06-13T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1237\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

private val alga1stExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1238\"},\"summary\":{\"value\":\"ALGA 1st Exam\"},\"description\":{\"value\":\"First exam of the ALGA course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-20T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-20T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1238\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private val alga2ndExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1239\"},\"summary\":{\"value\":\"ALGA 2nd Exam\"},\"description\":{\"value\":\"Second exam of the ALGA course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-21T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-21T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1239\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

private val m1FirstExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1240\"},\"summary\":{\"value\":\"M1 1st Exam\"},\"description\":{\"value\":\"First exam of the M1 course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-22T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-22T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1240\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private val m1SecondExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1241\"},\"summary\":{\"value\":\"M1 2nd Exam\"},\"description\":{\"value\":\"Second exam of the M1 course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-23T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-23T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1241\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

private val e1stExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1242\"},\"summary\":{\"value\":\"Eletronic 1st Exam\"},\"description\":{\"value\":\"First exam of the Eletronic course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-24T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-24T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1242\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"
private val e2ndExam =
    "{\"class\":[\"event\"],\"properties\":{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/1243\"},\"summary\":{\"value\":\"Eletronic 2nd Exam\"},\"description\":{\"value\":\"Second exam of the Eletronic course during the 1920v semester\"},\"categories\":{\"value\":\"Exam\"},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstart\":{\"value\":\"2020-03-25T14:00:00Z\"},\"dtend\":{\"value\":\"2020-03-25T16:30:00Z\"}}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rel/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/1243\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

// Lectures mock
private val pg11Dlectures =
    "{\"class\":[\"calendar\"],\"properties\":{\"type\":\"calendar\",\"properties\":{\"prodid\":{\"value\":\"/v0/courses/1/classes/1920v/sections/11D\"},\"version\":{\"value\":\"2.0\"}},\"subComponents\":[{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/45678\"},\"summary\":{\"value\":\"Theory Class WAD-1920v\"},\"description\":{\"value\":\"Theory Class of the WAD-1920v class.\"},\"categories\":{\"value\":[\"Lecture\",\"Theory Class\"]},\"dtstamp\":{\"value\":\"2020-02-10T10:34:24Z\"},\"dtstart\":{\"value\":\"2020-03-19T11:00:00Z\"},\"duration\":{\"value\":\"PT03H00M00S\"},\"rrule\":{\"value\":{\"freq\":\"WEEKLY\",\"until\":\"2020-06-10T00:00:00Z\",\"byDay\":[\"TH\"]}}}},{\"type\":\"event\",\"properties\":{\"uid\":{\"value\":\"event/45679\"},\"summary\":{\"value\":\"Theory Class WAD-1920v\"},\"description\":{\"value\":\"Theory Class of the WAD-1920v class.\"},\"categories\":{\"value\":[\"Lecture\",\"Theory Class\"]},\"dtstamp\":{\"value\":\"2020-02-10T10:34:24Z\"},\"dtstart\":{\"value\":\"2020-03-16T11:00:00Z\"},\"duration\":{\"value\":\"PT01H30M00S\"},\"rrule\":{\"value\":{\"freq\":\"WEEKLY\",\"until\":\"2020-06-10T00:00:00Z\",\"byDay\":[\"MO\"]}}}}]},\"entities\":[{\"class\":[\"class\",\"section\"],\"rel\":[\"/rel/class-section\"],\"properties\":{\"uid\":\"61D\",\"lecturer\":1010},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}],\"actions\":[{\"name\":\"search\",\"summary\":\"Search components\",\"method\":\"GET\",\"href\":\"/v0/courses/1/classes/1920v/calendar{?type,startBefore,startAfter,endBefore,endAfter,summary}\",\"isTemplated\":true,\"type\":\"application/x-www-form-urlencoded\",\"fields\":[{\"name\":\"type\",\"type\":\"text\",\"class\":\"https://example.org/param/free-text-query\"},{\"name\":\"startBefore\",\"type\":\"date\",\"class\":\"https://example.org/param/date-query\"},{\"name\":\"startAfter\",\"type\":\"date\",\"class\":\"https://example.org/param/date-query\"},{\"name\":\"endBefore\",\"type\":\"date\",\"class\":\"https://example.org/param/date-query\"},{\"name\":\"endAfter\",\"type\":\"date\",\"class\":\"https://example.org/param/date-query\"},{\"name\":\"summary\",\"type\":\"text\",\"class\":\"https://example.org/param/free-text-query\"}]},{\"name\":\"add-item\",\"title\":\"Add Item\",\"method\":\"POST\",\"href\":\"/v0/courses/1/classes/1920v/calendar\",\"isTemplated\":false,\"type\":\"application/json\",\"fields\":[]},{\"name\":\"batch-delete\",\"title\":\"Delete multiple items\",\"method\":\"DELETE\",\"isTemplated\":true,\"href\":\"/v0/courses/1/classes/1920v/calendar{?type}\",\"fields\":[{\"name\":\"type\",\"type\":\"text\",\"class\":\"https://example.org/param/free-text-query\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/61D/calendar\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v/61D\"}]}"

// Work assignments mock
private const val pg11DWorkAssignment1 =
    "{\"class\":[\"todo\"],\"properties\":{\"uid\":{\"value\":\"todo/123490\"},\"summary\":{\"value\":\"PG 1st Serie\"},\"description\":{\"value\":\"First serie of exercises for the PG course during the 1920v semester\"},\"attachment\":{\"value\":\"https://github.com/isel-leic-pg/1920v-public/wiki/phase-1\"},\"categories\":{\"value\":[\"Evaluation\",\"Assignment\",\"Programming\"]},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-12T12:24:50Z\"},\"due\":{\"value\":\"2020-03-19T23:59:59Z\"}},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rels/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/123490\"},{\"rel\":[\"service-doc\"],\"href\":\"https://github.com/isel-leic-pg/1920v-public/wiki/phase-1\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"}]}"

// Journal
private const val pgExamJournal =
    "{\"class\":[\"journal\"],\"properties\":{\"uid\":{\"value\":\"journal/123497\"},\"summary\":{\"value\":\"Error in 1st PG Exam\"},\"description\":{\"value\":\"The first exercise had and ambigous question that resulted in both answers B and C being correct. Therefore both will be awarded full marks.\"},\"categories\":{\"value\":[\"Error\",\"Evaluation\",\"Exam\",\"Programming\"]},\"created\":{\"value\":\"2020-02-10T10:34:20Z\"},\"dtstamp\":{\"value\":\"2020-02-12T12:24:50Z\"},\"dtstart\":{\"value\":\"2020-03-19T14:00:00Z\"},\"relatedTo\":[{\"value\":\"/v0/courses/1/classes/1920v/calendar/1234\"},{\"parameters\":{\"reltype\":\"SIBLING\"},\"value\":\"/v0/courses/1/classes/1920v/calendar/123485\"}]},\"entities\":[{\"class\":[\"class\"],\"rel\":[\"/rels/class\"],\"properties\":{\"classId\":\"1\",\"termId\":\"1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"term\"],\"href\":\"/v0/terms/1\"},{\"rel\":[\"course\"],\"href\":\"/v0/courses/1\"}]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/1/classes/1920v/calendar/123497\"},{\"rel\":[\"about\"],\"href\":\"/v0/courses/1/classes/1920v\"},{\"rel\":[\"related\"],\"href\":[\"/v0/courses/1/classes/1920v/calendar/1234\",\"/v0/courses/1/classes/1920v/calendar/123485\"]}]}"

