package org.ionproject.android.common.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import java.net.URI

/**
 *  This type represents a Class Section in the context of this application.
 */
@Entity(primaryKeys = ["id", "courseAcronym", "calendar_term"])
data class ClassSection(
    val id: String,
    val courseAcronym: String,
    @ColumnInfo(name = "calendar_term") val calendarTerm: String, //Should be a foreign key in the future
    @ColumnInfo(name = "calendar_uri") val calendarURI: URI?,
    val selfUri: URI,
    override var workerId: Int = 0
) : ICacheable

@Entity(primaryKeys = ["id", "courseAcronym", "calendar_term"])
open class ClassSummary(
    open val id: String,
    open val courseAcronym: String,
    @ColumnInfo(name = "calendar_term") open val calendarTerm: String, //Should be a foreign key in the future
    @ColumnInfo(name = "details_uri") open val detailsUri: URI,
    open val selfUri: URI,
    override var workerId: Int = 0
) : ICacheable {

    override fun equals(other: Any?): Boolean {
        val other = other as ClassSummary
        if (id == other.id && courseAcronym == other.courseAcronym && calendarTerm == other.calendarTerm
            && detailsUri == other.detailsUri && selfUri == other.selfUri
        ) {
            return true
        }
        return false
    }

    /**
     * Generated by the IDE
     */
    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + courseAcronym.hashCode()
        result = 31 * result + calendarTerm.hashCode()
        result = 31 * result + detailsUri.hashCode()
        result = 31 * result + selfUri.hashCode()
        result = 31 * result + workerId
        return result
    }

}

