package edu.isel.ion.android.common.ionwebapi

import android.util.Log
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.core.type.TypeReference
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.jsontype.NamedType
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import com.fasterxml.jackson.module.kotlin.readValue
import edu.isel.ion.android.common.EmbeddedEntity
import edu.isel.ion.android.common.EmbeddedLink
import edu.isel.ion.android.common.SirenEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.net.URI

private const val COURSES_PATH_V0 = "/v0/courses"
private const val CLASSES_PATH = "/classes"
private const val COURSES_PATH = "/courses"

class MockIonWebAPI : IIonWebAPI {

    private val objectMapper: ObjectMapper by lazy {
        ObjectMapper().apply {
            enable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            setSerializationInclusion(JsonInclude.Include.NON_NULL)
        }
    }

    private val jacksonObjMapper = jacksonObjectMapper()

    /*
        This is using the IO Dispacher, which is optimized to perform disk or network I/O
        outside of the main thread. Examples include using the Room component,
        reading from or writing to files, and running any network operations.
     */

    override suspend fun <T> getFromURI(uri: URI): SirenEntity<T> {
        val json = get(uri)
        return parse(json)
    }


    override suspend fun <T> getFromURI(uri: URI, clazz: Class<T>): T {
        val json = get(uri)
        return parse(json, clazz)
    }

    private suspend fun get(uri: URI): String =
        withContext(Dispatchers.IO) {
            route(uri)
        }

    private suspend fun <T> parse(json: String): SirenEntity<T> =
        withContext(Dispatchers.Default) {
            Log.println(Log.DEBUG,"COURSES","Started parsing to SirenEntity")
            val res = kotlin.runCatching {
                jacksonObjMapper.readValue<SirenEntity<T>>(json)
            }
            if(res.isFailure)
                Log.println(Log.DEBUG,"COURSES","Failed parsing to SirenEntity, exception : ${res.exceptionOrNull()}")
            else
                Log.println(Log.DEBUG,"COURSES","Successfully parsed to SirenEntity")
            res.getOrNull()!!
        }


    private suspend fun <T> parse(json: String, clazz: Class<T>): T =
        withContext(Dispatchers.Default) {
            objectMapper.readValue(json, clazz)
        }

    private fun route(uri: URI): String = when (uri.path) {
        COURSES_PATH_V0 -> allCoursesMock
        "${COURSES_PATH}/pg" -> pgMock
        "${COURSES_PATH}/e" -> eMock
        "${COURSES_PATH}/lsd" -> lsdMock
        "${COURSES_PATH}/m1" -> m1Mock
        "${COURSES_PATH}/alga" -> algaMock
        "${COURSES_PATH}/alga${CLASSES_PATH}" -> algaClassesMock
        "${COURSES_PATH_V0}/alga${CLASSES_PATH}/s1920v/1d" -> algaClassSectionMock
        else -> throw Exception("Uri not implemented or invalid")
    }

}

/*
    Computer generated mocks
 */

//All courses
private const val allCoursesMock =
    "{\"class\":[\"course\",\"collection\"],\"properties\":{},\"entities\":[{\"class\":[\"course\"],\"rel\":[\"item\"],\"properties\":{\"acronym\":\"PG\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pg\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pg/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]},{\"class\":[\"class\"],\"rel\":[\"item\"],\"properties\":{\"acronym\":\"E\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/e\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/e/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]},{\"class\":[\"class\"],\"rel\":[\"item\"],\"properties\":{\"acronym\":\"LSD\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lsd\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/lsd/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]},{\"class\":[\"class\"],\"rel\":[\"item\"],\"properties\":{\"acronym\":\"M1\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/m1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]},{\"class\":[\"class\"],\"rel\":[\"item\"],\"properties\":{\"acronym\":\"ALGA\"},\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/alga\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/alga/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}],\"actions\":[{\"name\":\"add-item\",\"title\":\"Add a new Course\",\"method\":\"POST\",\"href\":\"/v0/courses\",\"isTemplated\":false,\"type\":\"application/json\",\"fields\":[]},{\"name\":\"search\",\"title\":\"Search items\",\"method\":\"GET\",\"href\":\"/v0/courses\",\"isTemplated\":true,\"type\":\"application/vnd.siren+json\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses?page=1&limit=2\"},{\"rel\":[\"next\"],\"href\":\"/courses?page=2&limit=2\"},{\"rel\":[\"previous\"],\"href\":\"/courses?page=0&limit=2\"}]}"

//Courses
private const val pgMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PG\",\"name\":\"Programação\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pg/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pg\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pg/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pg\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pg\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pg\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pg\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pg/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val eMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"E\",\"name\":\"Eletrónica\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/e/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/e\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/e/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/e\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/e\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/e\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/e\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/e/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val lsdMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"LSD\",\"name\":\"Lógica de Sistemas Digitais\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lsd/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/lsd\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lsd/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/lsd\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/lsd\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/lsd\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lsd\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/lsd/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val m1Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"M1\",\"name\":\"Matemática I\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m1/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/m1\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m1/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/m1\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/m1\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/m1\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/m1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val algaMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"ALGA\",\"name\":\"Álgebra Linear e Geometria Analítica\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/alga/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/alga\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/alga/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/alga\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/alga\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/alga\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/alga\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/alga/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val acMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"AC\",\"name\":\"Arquitetura de Computadores\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ac/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ac\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ac/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ac\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ac\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ac\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ac\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ac/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val licMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"LIC\",\"name\":\"Laboratório de Informática e Computadores\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lic/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/lic\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lic/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/lic\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/lic\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/lic\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lic\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/lic/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val m2Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"M2\",\"name\":\"Matemática II\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m2/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/m2\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m2/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/m2\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/m2\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/m2\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/m2\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/m2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val peMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PE\",\"name\":\"Probabilidade e Estatística\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pe/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pe\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pe/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pe\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pe\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pe\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pe\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pe/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pooMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"POO\",\"name\":\"Programação Orientada por Objetos\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/poo/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/poo\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/poo/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/poo\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/poo\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/poo\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/poo\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/poo/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val aedMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"AED\",\"name\":\"Algoritmos e Estruturas de Dados\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/aed/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/aed\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/aed/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/aed\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/aed\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/aed\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/aed\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/aed/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val comMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"COM\",\"name\":\"Comunicações\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/com/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/com\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/com/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/com\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/com\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/com\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/com\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/com/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pscMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PSC\",\"name\":\"Programação em Sistemas Computacionais\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/psc/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/psc\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/psc/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/psc\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/psc\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/psc\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/psc\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/psc/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val si1Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SI1\",\"name\":\"Sistemas de Informação I\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si1/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/si1\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si1/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/si1\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/si1\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/si1\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/si1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val egpMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"EGP\",\"name\":\"Economia e Gestão de Projeto\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/egp/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/egp\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/egp/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/egp\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/egp\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/egp\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/egp\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/egp/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val cqfMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"CQF\",\"name\":\"Controlo de Qualidade e Fiabilidade\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cqf/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/cqf\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cqf/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/cqf\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/cqf\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/cqf\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cqf\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/cqf/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val lcMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"LC\",\"name\":\"Lógica e Computação\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lc/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/lc\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lc/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/lc\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/lc\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/lc\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/lc\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/lc/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pmMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PM\",\"name\":\"Programação de Microcontroladores\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pm/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pm\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pm/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pm\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pm\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pm\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pm\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pm/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pfMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PF\",\"name\":\"Programação Funcional\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pf/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pf\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pf/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pf\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pf\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pf\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pf\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pf/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val aveMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"AVE\",\"name\":\"Ambientes Virtuais de Execução\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ave/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ave\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ave/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ave\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ave\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ave\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ave\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ave/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val lsMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"LS\",\"name\":\"Laboratório de Software\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ls/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ls\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ls/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ls\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ls\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ls\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ls\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ls/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val rcpMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"RCP\",\"name\":\"Redes de Computadores\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/rcp/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/rcp\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/rcp/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/rcp\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/rcp\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/rcp\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/rcp\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/rcp/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val soMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SO\",\"name\":\"Sistemas Operativos\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/so/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/so\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/so/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/so\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/so\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/so\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/so\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/so/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val csmMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"CSM\",\"name\":\"Codificação de Sinais Multimédia\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/csm/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/csm\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/csm/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/csm\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/csm\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/csm\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/csm\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/csm/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val iaMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"IA\",\"name\":\"Inteligência Artificial\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ia/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ia\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ia/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ia\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ia\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ia\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ia\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ia/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val mpdMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"MPD\",\"name\":\"Modelação e Padrões de Desenho\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mpd/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/mpd\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mpd/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/mpd\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/mpd\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/mpd\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mpd\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/mpd/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val tjMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"TJ\",\"name\":\"Teoria de Jogos\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tj/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/tj\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tj/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/tj\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/tj\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/tj\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tj\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/tj/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pcMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PC\",\"name\":\"Programação Concorrente\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pc/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pc\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pc/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pc\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pc\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pc\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pc\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pc/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val piMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PI\",\"name\":\"Programação na Internet\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pi/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pi\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pi/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pi\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pi\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pi\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pi\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pi/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val si2Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SI2\",\"name\":\"Sistemas de Informação II\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si2/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/si2\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si2/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/si2\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/si2\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/si2\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si2\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/si2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val smMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SM\",\"name\":\"Sistemas Multimédia\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/sm/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/sm\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/sm/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/sm\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/sm\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/sm\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/sm\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/sm/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val pdmMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PDM\",\"name\":\"Programação em Dispositivos Móveis\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pdm/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/pdm\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pdm/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/pdm\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/pdm\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/pdm\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/pdm\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/pdm/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val riMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"RI\",\"name\":\"Redes de Internet\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ri/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ri\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ri/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ri\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ri\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ri\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ri\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ri/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val siMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SI\",\"name\":\"Segurança Informática\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/si\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/si\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/si\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/si\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/si\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/si/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val se1Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SE1\",\"name\":\"Sistemas Embebidos I\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se1/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/se1\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se1/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/se1\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/se1\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/se1\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se1\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/se1/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val mbMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"MB\",\"name\":\"Modelação Bayesiana\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mb/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/mb\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mb/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/mb\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/mb\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/mb\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/mb\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/mb/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val empMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"EMP\",\"name\":\"Empreendedorismo\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/emp/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/emp\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/emp/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/emp\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/emp\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/emp\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/emp\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/emp/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val gqsMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"GQS\",\"name\":\"Gestão da Qualidade em Saúde\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gqs/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/gqs\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gqs/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/gqs\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/gqs\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/gqs\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gqs\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/gqs/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val psMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"PS\",\"name\":\"Projeto e Seminário\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ps/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/ps\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ps/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/ps\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/ps\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/ps\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/ps\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/ps/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val cnMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"CN\",\"name\":\"Computação na Nuvem\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cn/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/cn\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cn/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/cn\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/cn\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/cn\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/cn\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/cn/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val dawMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"DAW\",\"name\":\"Desenvolvimento de Aplicações Web\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/daw/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/daw\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/daw/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/daw\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/daw\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/daw\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/daw\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/daw/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val se2Mock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"SE2\",\"name\":\"Sistemas Embebidos II\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se2/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/se2\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se2/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/se2\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/se2\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/se2\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/se2\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/se2/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val tarMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"TAR\",\"name\":\"Tecnologias Avançadas de Redes\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tar/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/tar\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tar/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/tar\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/tar\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/tar\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/tar\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/tar/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";
private const val gapMock =
    "{\"class\":[\"course\"],\"properties\":{\"acronym\":\"GAP\",\"name\":\"Gestão e Avaliação de Projetos\"},\"entities\":[{\"class\":[\"class\",\"collection\"],\"rel\":[\"class\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gap/classes\"},{\"rel\":[\"course\"],\"href\":\"/courses/gap\"}]},{\"class\":[\"event\",\"collection\"],\"rel\":[\"event\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gap/events\"},{\"rel\":[\"course\"],\"href\":\"/courses/gap\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete course\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/gap\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit course\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/gap\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/courses/gap\"},{\"rel\":[\"current\"],\"href\":\"/v0/courses/gap/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/courses\"}]}";

//Course classes
private const val algaClassesMock =
    "{\"class\":[\"class\"],\"properties\":{\"course\":\"ALGA\",\"calendar term\":\"1920v\"},\"entities\":[{\"class\":[\"class\",\"section\"],\"properties\":{\"id\":\"1d\"},\"rel\":[\"item\"],\"title\":\"Class Section of Course ALGA at Calendar Term 1920v\",\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/1920v/1d\"}]},{\"class\":[\"class\",\"section\"],\"properties\":{\"id\":\"1n\"},\"rel\":[\"item\"],\"title\":\"Class Section of Course ALGA at Calendar Term 1920v\",\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/1920v/1n\"}]},{\"class\":[\"calendar\"],\"rel\":[\"calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/s1920v/calendar\"}]}],\"actions\":[{\"name\":\"delete\",\"title\":\"Delete class\",\"method\":\"DELETE\",\"isTemplated\":false,\"href\":\"/v0/courses/alga/classes/1920v\",\"fields\":[]},{\"name\":\"edit\",\"title\":\"Edit class\",\"method\":\"PATCH\",\"isTemplated\":false,\"type\":\"application/json\",\"href\":\"/v0/courses/alga/classes/1920v\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/1920v\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/alga/classes/\"}]}"

//Class Section
private const val algaClassSectionMock =
    "{\"class\":[\"class\",\"section\"],\"properties\":{\"course\":\"ALGA\",\"class\":\"s1920v\",\"id\":\"1D\"},\"entities\":[{\"class\":[\"calendar\"],\"rel\":[\"/rel/calendar\"],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/s1920v/1d/calendar\"}]}],\"actions\":[{\"name\":\"enroll\",\"title\":\"Enroll class section\",\"method\":\"POST\",\"href\":\"/v0/courses/alga/classes/s1920v/1d/enroll\",\"type\":\"application/x-www-form-urlencoded\",\"fields\":[]}],\"links\":[{\"rel\":[\"self\"],\"href\":\"/v0/courses/alga/classes/s1920v/1d\"},{\"rel\":[\"collection\"],\"href\":\"/v0/courses/alga/classes/s1920v\"}]}"



